# Generated by Django 3.1.1 on 2020-12-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleria_videos', '0004_video_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='image',
            new_name='video',
        ),
    ]
