# Generated by Django 3.1.1 on 2020-12-26 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleria_videos', '0006_auto_20201210_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
