# Generated by Django 3.1.1 on 2020-12-13 17:11

from django.db import migrations, models
import galleria_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('about_us', models.TextField()),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=galleria_setting.models.upload_image_path)),
                ('copyright', models.CharField(max_length=200)),
                ('location', models.URLField()),
            ],
        ),
    ]
