# Generated by Django 3.1.1 on 2020-12-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleria_photos', '0002_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
