# Generated by Django 3.1.1 on 2020-12-19 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleria_photos', '0005_auto_20201218_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
